export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const INIT_TEAMS = "INIT_TEAMS";
export const SET_TEAMS = "SET_TEAMS";
export const FETCH_TEAMS = "FETCH_TEAMS";
export const FETCH_TEAMS_START = "FETCH_TEAMS_START";
export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_FAILED = "FETCH_TEAMS_FAILED";
export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const RESET_TEAMS = "RESET_TEAMS";

export const ADD_MOOD = "ADD_MOOD";
